name: Release Wheels

on:
  workflow_dispatch:
    inputs:
      python_versions:
        description: 'Python version (e.g. 3.9) or range (e.g. 3.8-3.14) to build'
        required: false
        default: ''
  release:
    types:
      - created
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/release-wheel.yml'
      - '.github/workflows/wheels-common.yml'
      - 'tools/python_bind/setup.py'
      - 'tools/python_bind/pyproject.toml'
      - 'tools/python_bind/Makefile'
      - 'tools/python_bind/README.md'

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  format_check:
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || github.event_name == 'release'
    uses: ./.github/workflows/format-check.yml
    with:
      is_pull_request: ${{ github.event_name == 'pull_request' }}

  build_wheels:
    needs:
      - format_check
    uses: ./.github/workflows/wheels-common.yml
    with:
      python_versions: ${{ inputs.python_versions }}
      mode: release
      set_nightly_version: false
      pybind11_findpython_off: true
      linux_x86_python: '3.13'
      linux_arm_python: '3.13'
      mac_python: '3.13'
      cibuildwheel_version: '3.4.0'
      enable_macos_x86: false
      caller_event_name: ${{ github.event_name }}
    secrets: inherit
